{"name": "The user should be able to view orders repository", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1f44c75dd32sm52130865ad.12 - gsmtp')\n", "trace": "  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 108, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "steps": [{"name": "And Scroll through menu to view planning option", "status": "passed", "start": 1716787684764, "stop": 1716787688296}, {"name": "And Scroll through menu to view orders menu", "status": "passed", "start": 1716787688296, "stop": 1716787688610}, {"name": "And Click on orders button", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1f44c75dd32sm52130865ad.12 - gsmtp')\n", "trace": "  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 108, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "attachments": [{"name": "screenshot", "source": "d874e268-54bc-45e1-a069-169c6fa380d6-attachment.png", "type": "image/png"}], "start": 1716787688610, "stop": 1716787714396}], "start": 1716787683759, "stop": 1716787714397, "uuid": "110a4b83-dd98-471b-9cbf-4a58d9aa7769", "historyId": "8861ba84460d4043a237208c15b1b0a1", "fullName": "Verify the TMS functionality: The user should be able to view orders repository", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Orders"}, {"name": "feature", "value": "Verify the TMS functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}