{"name": "The user should be able to view orders repository", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d2e1a72fcca58-70d2ab47272sm4078901b3a.208 - gsmtp')\n", "trace": "  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 109, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "steps": [{"name": "And Scroll through menu to view planning option", "status": "passed", "start": 1721800243066, "stop": 1721800244842}, {"name": "And Scroll through menu to view orders menu", "status": "passed", "start": 1721800244842, "stop": 1721800245222}, {"name": "And Click on orders button", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d2e1a72fcca58-70d2ab47272sm4078901b3a.208 - gsmtp')\n", "trace": "  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 109, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "attachments": [{"name": "screenshot", "source": "2e6cfaab-7224-4556-8e07-7b946e730438-attachment.png", "type": "image/png"}], "start": 1721800245222, "stop": 1721800251308}], "start": 1721800242082, "stop": 1721800251308, "uuid": "a0b79093-d8d0-4893-9596-e238841d0308", "historyId": "8861ba84460d4043a237208c15b1b0a1", "fullName": "Verify the TMS functionality: The user should be able to view orders repository", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Orders"}, {"name": "feature", "value": "Verify the TMS functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}