{"name": "The user should be able to view orders repository", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1ff5929ad84sm98632555ad.270 - gsmtp')\n", "trace": "  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 109, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "steps": [{"name": "And Scroll through menu to view planning option", "status": "passed", "start": 1723014293571, "stop": 1723014296447}, {"name": "And Scroll through menu to view orders menu", "status": "passed", "start": 1723014296448, "stop": 1723014296738}, {"name": "And Click on orders button", "status": "broken", "statusDetails": {"message": "smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. For more\\n5.7.9 information, go to\\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1ff5929ad84sm98632555ad.270 - gsmtp')\n", "trace": "  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 109, in after_step\n    s.login(fromaddr, \"E$$pl@2022!#21\")\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 750, in login\n    raise last_exception\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 739, in login\n    (code, resp) = self.auth(\n  File \"C:\\Users\\sonalib\\AppData\\Local\\Programs\\Python\\Python310\\lib\\smtplib.py\", line 662, in auth\n    raise SMTPAuthenticationError(code, resp)\n"}, "attachments": [{"name": "screenshot", "source": "c45cac27-4c3f-4145-8355-eb574308e72a-attachment.png", "type": "image/png"}], "start": 1723014296738, "stop": 1723014303335}], "start": 1723014292566, "stop": 1723014303335, "uuid": "5cf56549-d9dd-4c4a-a9ad-2b955eaaa5e8", "historyId": "8861ba84460d4043a237208c15b1b0a1", "fullName": "Verify the TMS functionality: The user should be able to view orders repository", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Orders"}, {"name": "feature", "value": "Verify the TMS functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}